name: Déploiement de l’API Vite ma dose

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Rsync Deployments Action
      uses: Burnett01/rsync-deployments@5.1
      with:
          path: ./
          switches: -avz --delete --exclude ".git*"
          remote_path: ${{ secrets.DEPLOY_PATH }}
          remote_host: ${{ secrets.DEPLOY_IP }}
          remote_user: ubuntu
          remote_key: ${{ secrets.DEPLOY_KEY }}
